sonar.projectKey=mern-app
sonar.projectName=MERN Application
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8


# it means to scan the files under source folder
sonar.sources=src
# it means to exclude these fodlers
sonar.exclusions=node_modules/**,build/**,dist/**

# Code coverage (Jest generates lcov.info)
sonar.javascript.lcov.reportPaths=coverage/lcov.info


