apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 389275957030.dkr.ecr.us-west-2.amazonaws.com/mern-backend:v5
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: mern-config